#!/usr/bin/env node
// scripts/update_baselines.js
// Fetches live mock API response and writes it to cypress/fixtures/ai_baselines.json.
// Run manually: npm run cypress:update-baselines
// NEVER add this script to .github/workflows/cypress.yml

const http = require('http');
const fs   = require('fs');
const path = require('path');

const API_BASE    = process.env.API_URL || 'http://localhost:3001';
const FIXTURE     = path.join(__dirname, '../cypress/fixtures/ai_baselines.json');
const FIXED_PAYLOAD = { query: 'flight BKK to TYO', role: 'Staff', date: '2026-08-01' };

function request(url, options, body) {
  return new Promise((resolve, reject) => {
    const req = http.request(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(data) }); }
        catch (e) { reject(new Error('Failed to parse JSON response')); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

async function main() {
  // Step 1: health check
  console.log(`Checking API at ${API_BASE}/health …`);
  try {
    await request(`${API_BASE}/health`, { method: 'GET' });
  } catch (err) {
    console.error(`\n❌ API not reachable at ${API_BASE}`);
    console.error('   Start it first: npm run start:api:mock');
    process.exit(1);
  }

  // Step 2: fetch baseline payload
  console.log(`Fetching baselines for payload: ${JSON.stringify(FIXED_PAYLOAD)}`);
  const bodyStr = JSON.stringify(FIXED_PAYLOAD);
  const url = new URL(`${API_BASE}/api/search`);
  const options = {
    hostname: url.hostname,
    port: url.port || 3001,
    path: url.pathname,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(bodyStr),
    },
  };

  let res;
  try {
    res = await request(`${API_BASE}/api/search`, options, bodyStr);
  } catch (err) {
    console.error(`\n❌ Search request failed: ${err.message}`);
    process.exit(1);
  }

  if (res.status !== 200 || !res.body.data || res.body.data.length === 0) {
    console.error(`\n❌ Unexpected response (${res.status}): ${JSON.stringify(res.body)}`);
    process.exit(1);
  }

  const data = res.body.data;
  const first = data[0];

  const baseline = {
    _note: 'Generated by: npm run cypress:update-baselines. Do NOT edit manually.',
    _generatedAt: new Date().toISOString().split('T')[0],
    payload: FIXED_PAYLOAD,
    expectedResultCount: data.length,
    firstResult: {
      airline: first.airline,
      cabinClass: first.cabinClass,
      price: first.price,
      policyCompliant: first.policyCompliant,
      policyFlags: first.policyFlags || [],
    },
  };

  fs.writeFileSync(FIXTURE, JSON.stringify(baseline, null, 2));
  console.log(`\n✅ Baselines updated — commit cypress/fixtures/ai_baselines.json`);
  console.log(`   Results: ${data.length} flights`);
  console.log(`   First:   ${first.airline} · ${first.cabinClass} · $${first.price}`);
}

main();
